### PR TITLE
Use bootstrap styles

### PR DESCRIPTION
**Pull request by miparnisari**
- Remove INSTALL, move installation instructions to README. 
  - Remove existing CSS styles and replace them with bootstrap (except for `prettify.css`)
  - Fix https://github.com/petdance/perl101/issues/10
  - Update Google Analytics script

### CODE REVIEW

**Comment by miparnisari** [comment]
@petdance can you review this?

**Comment by miparnisari** [comment]
@petdance ??

**Comment by petdance** [comment]
Sorry for the delay.  Can you tell me more about "Remove existing CSS styles and replace them with bootstrap (except for prettify.css)"?  What is bootstrap and why do we want it?

**Comment by miparnisari** [comment]
@petdance https://getbootstrap.com/ :) it makes the site look nicer

**Comment by petdance** [comment]
Is there a way we can get the styling without the Javascript?

**Comment by miparnisari** [comment]
@petdance I removed Bootstrap JS but we need jQuery to do the ajax that sends the email.

**Comment by petdance** [comment]
OK, thanks.

I had forgotten about the email part.  I think I'd like to throw it away.  no reason to let spammers send junk.  

I will try to take a look next week.  I have a conference talk on Saturday I have to work on.

**Comment by petdance** [comment]
Thanks for this.  We need to get rid of the formmail part.  I don't want there to be any emailing going on.  It was a good idea 10 years ago, and now it's not worth putting back.  Is that something you can easily update?

**Comment by miparnisari** [comment]
Sure I can remove it @petdance.

**Comment by miparnisari** [comment]
Is there a file missing? The README mentions a file `section.tt` but it's not here

**Comment by petdance** [comment]
I've merged and deployed this.  Thanks so much for working on it.

Please note that I've also created a `dev` branch now, so make PRs against that.

**Pull request closed without merging**
